(function(){
  var sb=window.supabaseClient;if(!sb)return;
  var me=null,profile=null,snapshot=null,selectedTradeId=null;
  var $=function(id){return document.getElementById(id)};
  var el={message:$('message'),setup:$('setup'),setupState:$('setup-state'),app:$('app'),request:$('request-import'),activate:$('activate-import'),search:$('player-search'),searchBtn:$('search-btn'),results:$('search-results'),refresh:$('refresh-btn'),list:$('trade-list'),empty:$('empty-detail'),detail:$('trade-detail'),status:$('trade-status'),title:$('trade-title'),meta:$('trade-meta'),mine:$('my-offer'),theirs:$('their-offer'),inventory:$('inventory'),save:$('save-offer'),send:$('send-offer'),confirm:$('confirm-trade'),close:$('close-trade')};
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function msg(text,error){el.message.textContent=text||'';el.message.className='message'+(error?' error':'')}
  async function invoke(action,body,mutating){var sessionResult=await sb.auth.getSession();var session=sessionResult.data&&sessionResult.data.session;if(sessionResult.error||!session)throw new Error('Bitte zuerst anmelden.');sb.functions.setAuth(session.access_token);var payload=Object.assign({action:action},body||{});if(mutating)payload.clientActionId=crypto.randomUUID();var r=await sb.functions.invoke('cursor-clicker-security',{body:payload,headers:{Authorization:'Bearer '+session.access_token}});if(r.error||r.data&&r.data.error)throw new Error(r.data&&r.data.error||'Serveranfrage fehlgeschlagen.');return r.data}
  async function init(){var s=(await sb.auth.getSession()).data.session;if(!s){msg('Bitte zuerst anmelden.',true);return}me=s.user.id;profile=(await sb.from('profiles').select('role,username').eq('id',me).maybeSingle()).data;await load()}
  async function load(){try{snapshot=await invoke('trading_snapshot');var active=snapshot.accountState==='active';el.setup.classList.toggle('hidden',active);el.app.classList.toggle('hidden',!active);if(!active){var st=await invoke('status');var m=st.migration;el.setupState.textContent=m?'Status: '+m.status+(m.riskFlags&&m.riskFlags.length?' · Prüfung erforderlich: '+m.riskFlags.join(', '):''):'Noch kein Import beantragt.';return}renderTrades();renderDetail()}catch(e){msg(e.message,true)}}
  function other(t){return t.initiator_id===me?{id:t.recipient_id,name:t.recipient_username,pid:t.recipient_player_id}:{id:t.initiator_id,name:t.initiator_username,pid:t.initiator_player_id}}
  function renderTrades(){var rows=snapshot.trades||[];el.list.innerHTML=rows.length?rows.map(function(t){var o=other(t);return '<button class="trade-row '+(t.id===selectedTradeId?'active':'')+'" data-id="'+t.id+'"><span><strong>'+esc(o.name)+'</strong><br><span class="player-id">'+esc(o.pid)+'</span></span><span class="status '+esc(t.status)+'">'+esc(t.status)+'</span></button>'}).join(''):'<p class="muted">Noch keine Trades.</p>';el.list.querySelectorAll('[data-id]').forEach(function(b){b.onclick=function(){selectedTradeId=b.dataset.id;renderTrades();renderDetail()}})}
  function chips(items){return items.length?items.map(function(x){var s=x.snapshot||{};return '<span class="item-chip">'+esc(s.icon||'🖱️')+' '+esc(s.name||s.catalogId)+'</span>'}).join(''):'<span class="muted">Noch nichts ausgewählt</span>'}
  function renderDetail(){var t=(snapshot.trades||[]).find(function(x){return x.id===selectedTradeId});el.empty.classList.toggle('hidden',!!t);el.detail.classList.toggle('hidden',!t);if(!t)return;var o=other(t),items=t.items||[],my=items.filter(function(x){return x.offeredBy===me}),their=items.filter(function(x){return x.offeredBy!==me});el.status.textContent=t.status;el.status.className='status '+t.status;el.title.textContent='Trade mit '+o.name;el.meta.textContent='Revision '+t.revision+' · läuft bis '+new Date(t.expires_at).toLocaleString('de-DE');el.mine.innerHTML=chips(my);el.theirs.innerHTML=chips(their);var editable=t.status==='draft'||t.status==='offered';el.inventory.innerHTML=(snapshot.inventory||[]).map(function(i){var locked=i.trade_lock_id&&i.trade_lock_id!==t.id,checked=my.some(function(x){return x.itemId===i.id}),d=i.item_data||{};return '<label class="inventory-item '+(locked?'locked':'')+'"><input type="checkbox" value="'+i.id+'" '+(checked?'checked ':'')+(locked||!editable?'disabled':'')+'><span class="item-icon">'+esc(d.icon||'🖱️')+'</span><span><strong>'+esc(d.name||i.catalog_id)+'</strong><br><span class="player-id">'+esc(d.rarity||'')+'</span></span></label>'}).join('')||'<p class="muted">Keine handelbaren Duplikate.</p>';el.save.disabled=!editable;el.send.disabled=t.status!=='draft';el.confirm.disabled=t.status!=='offered';el.close.disabled=!editable;el.close.textContent=t.initiator_id===me?'Trade abbrechen':'Trade ablehnen'}
  async function mutate(action,body,success){try{msg('Wird gespeichert …');await invoke(action,body,true);msg(success||'Gespeichert.');await load()}catch(e){msg(e.message,true)}}
  el.request.onclick=async function(){try{await invoke('request_legacy_migration',{},true);if(profile&&profile.role==='owner'){await invoke('owner_review_migration',{targetId:me,decision:'approved',note:'Owner-Selbstfreigabe im Testbereich'},true);msg('Import geprüft und Trading aktiviert.')}else msg('Import beantragt. Ein Owner muss ihn freigeben.');await load()}catch(e){msg(e.message,true)}};
  el.activate.onclick=function(){mutate('activate_trading',{},'Trading-Inventar aktiviert.')};
  el.searchBtn.onclick=async function(){var q=el.search.value.trim();if(q.length<3){msg('Bitte mindestens 3 Zeichen eingeben.',true);return}try{var rows=await invoke('search_players',{query:q});el.results.innerHTML=rows.length?rows.map(function(p){return '<div class="result"><span><strong>'+esc(p.username)+'</strong><br><span class="player-id">'+esc(p.player_id)+'</span></span><button class="btn" data-target="'+p.id+'">Trade starten</button></div>'}).join(''):'<p class="muted">Niemand gefunden.</p>';el.results.querySelectorAll('[data-target]').forEach(function(b){b.onclick=async function(){try{var t=await invoke('create_trade',{targetId:b.dataset.target},true);selectedTradeId=t.id;msg('Trade erstellt.');await load()}catch(e){msg(e.message,true)}}})}catch(e){msg(e.message,true)}};
  el.refresh.onclick=load;el.save.onclick=function(){var ids=Array.from(el.inventory.querySelectorAll('input:checked')).map(function(i){return i.value});mutate('set_offer',{tradeId:selectedTradeId,itemIds:ids},'Auswahl gespeichert.')};el.send.onclick=function(){mutate('send_offer',{tradeId:selectedTradeId},'Angebot gesendet.')};el.confirm.onclick=function(){var t=snapshot.trades.find(function(x){return x.id===selectedTradeId});if(t)mutate('confirm_trade',{tradeId:t.id,revision:t.revision},'Bestätigung gespeichert.')};el.close.onclick=function(){var t=snapshot.trades.find(function(x){return x.id===selectedTradeId});if(t&&confirm('Diesen Trade wirklich beenden?'))mutate('close_trade',{tradeId:t.id,mode:t.initiator_id===me?'cancel':'decline'},'Trade beendet.')};
  init();
})();
