const theme=document.createElement('link');theme.rel='stylesheet';theme.href='arcade.css';document.head.appendChild(theme);
const readable=document.createElement('link');readable.rel='stylesheet';readable.href='readability.css';document.head.appendChild(readable);
const factorsStyle=document.createElement('link');factorsStyle.rel='stylesheet';factorsStyle.href='factors.css';document.head.appendChild(factorsStyle);
const G=Game,$=id=>document.getElementById(id),key='lucky-loot-arcade-v1';let state=G.initial(),page='crates',filter='Alle',search='',source='',target='',factor=1.1;
try{const saved=JSON.parse(localStorage.getItem(key));if(G.valid(saved))state=saved}catch{}G.accrue(state);
const money=v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(v)+' ◉';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('Speicher voll oder deaktiviert – Fortschritt bleibt nur für diese Sitzung.')}}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function icon(kind){return kind==='Messer'?'⚔':kind==='Handschuhe'?'♧':'⌁'}
function art(item){return `<div class="item-art" style="--rarity:${G.tiers[item.tier].color}"><span>${icon(item.kind)}</span><small>${item.kind.toUpperCase()} / PLATZHALTER</small></div>`}
function box(c){return `<div class="box-stage" style="--box:${c.color}"><div class="crate-box"><div class="crate-lid"></div><span class="crate-sticker">✳</span><span class="crate-lock"></span></div><span class="spark s1">✦</span><span class="spark s2">✧</span></div>`}
function card(x,actions=true){const i=G.catalog[x.id],t=G.tiers[i.tier];return `<article class="item-card">${art(i)}<div class="item-info"><small style="color:${t.color}">${t.name}</small><h3>${i.name}</h3><p>${money(i.value)}</p>${actions?`<div class="item-actions"><button data-sell="${x.uid}">Verkaufen</button><button data-deposit="${x.uid}">Zur Bank ↗</button></div>`:''}</div></article>`}
function heading(k,h,p){return `<p class="eyebrow">${k}</p><h1>${h}</h1><p class="subtitle">${p}</p>`}
function stats(){return `<div class="stats"><div><span>Geöffnete Kisten</span><strong>${state.opened}</strong></div><div><span>Entdeckt</span><strong>${state.found.length}<small> / 250</small></strong></div><div><span>Bankeinkommen</span><strong id="rate">${money(G.rate(state))}<small> / s</small></strong></div></div>`}
function render(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('balance').textContent=money(state.coins);$('inv-count').textContent=state.inventory.length;const el=$('page');
if(page==='crates'){el.innerHTML=`<section class="welcome"><div>${heading('EIN BISSCHEN GLÜCK. VIELE MÖGLICHKEITEN.','Was steckt in deiner<br>nächsten Kiste?','Öffnen, sammeln, weitermachen. Dein nächster Lieblingsfund wartet schon.')}<a class="text-link" href="#crate-grid">Kisten entdecken ↓</a></div><div class="welcome-art">${box(G.crates[0])}<span class="round-label">DEIN ERSTER<br><b>Glücksmoment!</b></span></div></section>${stats()}<div class="section-title"><h2>Der Kistenladen <span>12</span></h2><span class="muted">Spielgeld rein. Überraschung raus.</span></div><div class="tabs"><button data-filter="Alle" class="${filter==='Alle'?'selected':''}">Alle Kisten</button><button data-filter="Gratis" class="${filter==='Gratis'?'selected':''}">Für lau</button><button data-filter="Kaufbar" class="${filter==='Kaufbar'?'selected':''}">Mit Münzen</button></div><div class="crate-grid" id="crate-grid">${G.crates.filter(c=>filter==='Alle'||(filter==='Gratis'?c.price===0:c.price>0)).map(c=>`<article class="crate-card"><div class="card-top"><span>${c.id===0?'DEIN STARTPUNKT':'KOLLEKTION '+String(c.id).padStart(2,'0')}</span>${c.id===0?'<b>GRATIS</b>':''}</div>${box(c)}<h3>${c.name} Case</h3><p>${c.id===0?'Kleine Funde, große Möglichkeiten.':'Neue Chancen für deine Sammlung.'}</p><button class="open-btn ${c.id===0?'primary':''}" data-open="${c.id}">${c.price?money(c.price)+' · Öffnen':'Gratis öffnen →'}</button><details><summary>Dropchancen ansehen</summary>${G.probabilities(c.id).map((p,i)=>`<div class="odds"><span>${G.tiers[i].name}</span><b>${(p*100).toLocaleString('de-DE',{maximumFractionDigits:4})} %</b></div>`).join('')}</details></article>`).join('')}</div><p class="footnote">Alle Gegenstände sind vorläufige Platzhalter. Die drei ultraseltenen Funde haben zusammen in jeder Kiste 0,001 % Chance.</p>`}
if(page==='inventory'){renderInventory(el)}
if(page==='bank'){el.innerHTML=heading('LASS DEINE FUNDE ARBEITEN','Deine kleine Schatzbank.','0,1 % des Gegenstandswerts pro Sekunde. Einnahmen sammeln sich hier. Hole sie ab, wenn du sie ausgeben möchtest.')+stats()+`<button class="primary collect-bank" id="collect-bank"><span>◉ BANKGELD ABHOLEN</span><strong id="bank-pending">${money(state.bankPending||0)}</strong><small>Gesammelte Einnahmen auf dein Konto übertragen</small></button><div class="section-title"><h2>Bankplätze <span>${state.bank.length} / ${state.slots}</span></h2><button class="primary" id="buy-slot">Platz kaufen · ${money(G.slotCost(state))}</button></div><div class="item-grid">${state.bank.map(x=>`<article class="item-card">${art(G.catalog[x.id])}<div class="item-info"><h3>${G.catalog[x.id].name}</h3><p>+ ${money(G.catalog[x.id].value*.001)} / s</p><button data-withdraw="${x.uid}">Zurück ins Inventar</button></div></article>`).join('')}${Array.from({length:state.slots-state.bank.length},()=>`<button class="empty-slot" data-page="inventory"><span>＋</span><h3>Ein Platz für deinen Fund</h3><p>Im Inventar einen Gegenstand einlegen</p></button>`).join('')}</div><p class="footnote">Offline-Einkommen: maximal 4 Stunden. Die Bankrate ist ein vorläufiger Testwert.</p>`}
if(page==='upgrade'){
const selected=state.inventory.find(x=>x.uid===source),options=selected?G.upgradeOptions(selected.id,factor):[],dest=options[0],prob=selected&&dest?G.chance(G.catalog[selected.id],dest):.64;
el.innerHTML=heading('DEIN EINSATZ. DEIN FAKTOR.','Wie groß soll der Sprung sein?','Wähle den Wertfaktor. Ein passender Gegenstand wird beim Versuch automatisch ausgelost.')+`<div class="upgrade-panel"><div><label for="source">1. Dein Einsatz</label><select id="source"><option value="">Gegenstand auswählen</option>${state.inventory.filter(x=>!x.locked).map(x=>`<option value="${x.uid}" ${x.uid===source?'selected':''}>${G.catalog[x.id].name} · ${money(G.catalog[x.id].value)}</option>`).join('')}</select>${selected?art(G.catalog[selected.id]):'<div class="upgrade-empty">＋</div>'}<p>${selected?money(G.catalog[selected.id].value):'Wähle einen Fund aus dem Inventar'}</p></div><div class="chance"><div class="chance-ring" style="--chance:${prob*100}%"><strong>${(prob*100).toLocaleString('de-DE',{maximumFractionDigits:2})}%</strong><small>ERFOLGSCHANCE</small></div><span>Maximal 64 %</span></div><div><label>2. Wie stark aufwerten?</label><div class="factor-buttons">${G.multipliers.map(m=>`<button data-factor="${m}" aria-pressed="${m===factor}">×${m.toLocaleString('de-DE',{minimumFractionDigits:1})}</button>`).join('')}</div><div class="upgrade-empty">✧</div><p>${selected&&dest?`Ziel: mindestens ${money(G.catalog[selected.id].value*factor)}<br>Passender Katalogwert: ${money(dest.value)}<br>${options.length} mögliche Gegenstände · Auswahl automatisch`:selected?'Kein passender Gegenstand für diesen Faktor vorhanden.':'Der Wert deines Einsatzes bestimmt den Zielwert.'}</p></div></div><div class="upgrade-footer"><p>Bei Fehlschlag geht dein Einsatz verloren.<br>Bei Wertlücken gilt der nächsthöhere Katalogwert; die Chance passt sich an.</p><button class="primary" id="upgrade-button" ${!selected||!dest?'disabled':''}>×${factor.toLocaleString('de-DE')} Aufwertung versuchen ↗</button></div>`;
}
if(page==='collection'){el.innerHTML=heading('DAS SAMMELALBUM','250 Gründe, neugierig zu bleiben.',`${state.found.length} entdeckt. Waffen, Messer und Handschuhe – inklusive drei ultraseltener Funde.`)+`<label class="search-label" for="search">Sammlung durchsuchen</label><input id="search" type="search" placeholder="Name oder Gegenstandsart …" value="${esc(search)}"><div class="item-grid" id="album"></div>`;renderAlbum()}
updateLive();}
function renderAlbum(){const list=G.catalog.filter(x=>(x.name+' '+x.kind).toLowerCase().includes(search.toLowerCase()));$('album').innerHTML=list.map(i=>`<article class="item-card album ${state.found.includes(i.id)?'found':''}">${art(i)}<div class="item-info"><small>${G.tiers[i.tier].name} · ${state.found.includes(i.id)?'ENTDECKT':'NOCH OFFEN'}</small><h3>${i.name}</h3><p>${money(i.value)}</p></div></article>`).join('')||'<p>Keine passenden Gegenstände.</p>'}
function updateLive(){$('balance').textContent=money(state.coins);if($('bank-pending'))$('bank-pending').textContent=money(state.bankPending||0);if($('collect-bank'))$('collect-bank').disabled=!(state.bankPending>0);document.querySelectorAll('[data-open]').forEach(b=>{const c=G.crates[Number(b.dataset.open)],seconds=Math.max(0,Math.ceil((8000-(Date.now()-state.lastFree))/1000));b.disabled=c.price>state.coins||(!c.price&&seconds>0);if(!c.price)b.textContent=seconds?`Neue Gratis-Kiste in ${seconds} s`:'Gratis öffnen →'})}
let revealTimer;
const motionOff=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
let lastCrate=0;
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)lastCrate=Number(b.dataset.open)},true);
function reveal(x,title='DEIN NEUER FUND'){
 const item=G.catalog[x.id],dialog=$('reveal');clearTimeout(revealTimer);dialog.classList.remove('fund-ready');dialog.classList.add('unpacking');
 document.querySelector('#reveal .eyebrow').textContent=G.crates[lastCrate].name.toUpperCase()+' CASE · DAS FUNDKARUSSELL';
 const pool=G.catalog.filter(i=>G.probabilities(lastCrate)[i.tier]>0);
 const entries=Array.from({length:44},()=>pool[Math.floor(Math.random()*pool.length)]);entries[37]=item;
 $('reveal-content').innerHTML='<p class="opening-caption">Welcher Fund bleibt am Zeiger stehen?</p><div class="reel-window"><span class="reel-pointer" aria-hidden="true">▼</span><div class="reel-track">'+entries.map((i,n)=>`<div class="reel-ticket ${n===37?'winning-ticket':''}" style="--rarity:${G.tiers[i.tier].color}">${art(i)}<strong>${i.name}</strong><small>${G.tiers[i.tier].name}</small></div>`).join('')+'</div><span class="reel-center" aria-hidden="true"></span></div><div class="reel-labels"><span>◂ MÖGLICHE FUNDE</span><span>DER ZEIGER ENTSCHEIDET ▾</span></div><p class="reel-disclaimer">Das Band zeigt eine Auswahl möglicher Gegenstände, nicht deren Drop-Häufigkeit. Vorbeiziehende Funde verändern deine Chance nicht.</p>';
 $('keep').hidden=true;dialog.showModal();
 const finish=()=>{dialog.classList.remove('unpacking');dialog.classList.add('fund-ready');dialog.style.setProperty('--fund-color',G.tiers[item.tier].color);document.querySelector('#reveal .eyebrow').textContent=title;$('reveal-content').innerHTML='<div class="fund-rays" aria-hidden="true"></div>'+art(item)+`<div class="rarity-stamp" style="color:${G.tiers[item.tier].color}">${G.tiers[item.tier].name}</div><h2>${item.name}</h2><p>${money(item.value)} · ${item.kind}</p><small class="receipt">FUNDNOTIZ NR. ${String(state.opened).padStart(5,'0')} · GUT AUFHEBEN!</small>`;$('keep').hidden=false;$('keep').focus()};
 const track=dialog.querySelector('.reel-track');
 const distance=37*154+71;
 if(!motionOff())track.animate([{transform:'translateX(calc(50% - 71px))'},{transform:`translateX(calc(50% - ${distance}px))`}],{duration:4700,easing:'cubic-bezier(.12,.68,.16,1)',fill:'forwards'});
 revealTimer=setTimeout(finish,motionOff()?0:5100);
}
$('reveal').addEventListener('close',()=>{clearTimeout(revealTimer);$('keep').hidden=false;$('reveal').classList.remove('unpacking','fund-ready')});
let upgrading=false;
document.addEventListener('click',e=>{
 const b=e.target.closest('#upgrade-button');if(!b)return;
 e.stopImmediatePropagation();if(upgrading)return;
 try{
  const entry=state.inventory.find(x=>x.uid===source);if(!entry)throw Error('Wähle deinen Einsatz.');
  G.accrue(state);const {dest,p,roll,result}=G.upgradeByFactor(state,source,factor);save();upgrading=true;
  const d=$('reveal');clearTimeout(revealTimer);d.classList.remove('unpacking','fund-ready');d.classList.add('upgrade-spinning');
  document.querySelector('#reveal .eyebrow').textContent='DIE GLÜCKSMASCHINE';
  $('reveal-content').innerHTML=`<p class="opening-caption">${G.catalog[entry.id].name} → ${dest.name}</p><div class="upgrade-dial" style="--arc:${p*360}deg"><div class="dial-face"></div><div class="dial-needle"><i></i></div><div class="dial-hub">✦</div></div><div class="dial-legend"><span>■ Erfolg ${(p*100).toLocaleString('de-DE',{maximumFractionDigits:2})} %</span><span>■ Fehlschlag</span></div><p id="spin-status" role="status">Die Nadel dreht sich …</p>`;
  $('keep').hidden=true;$('close-reveal').hidden=true;d.showModal();
  d.querySelector('.dial-needle').animate([{transform:'rotate(0deg)'},{transform:`rotate(${1800+roll*360}deg)`}],{duration:motionOff()?1:3900,easing:'cubic-bezier(.1,.7,.15,1)',fill:'forwards'});
  revealTimer=setTimeout(()=>{upgrading=false;source='';target='';render();$('close-reveal').hidden=false;$('keep').hidden=false;d.classList.remove('upgrade-spinning');d.classList.add('upgrade-result');$('spin-status').textContent=result?'Geschafft! Dein neuer Fund liegt im Inventar.':'Leider vorbei. Dein Einsatz ist verloren.';$('spin-status').className=result?'result-success':'result-failure';$('keep').textContent='Weiter sammeln →';if(result){document.querySelector('#reveal .eyebrow').textContent='AUFWERTUNG GELUNGEN';$('spin-status').insertAdjacentHTML('afterend',`<h2>${dest.name}</h2><p>${money(dest.value)}</p>`)}},motionOff()?1:4300);
 }catch(err){upgrading=false;toast(err.message)}
},true);
$('reveal').addEventListener('cancel',e=>{if(upgrading)e.preventDefault()});
$('reveal').addEventListener('close',()=>{$('close-reveal').hidden=false;$('keep').textContent='Ab ins Inventar →';$('reveal').classList.remove('upgrade-spinning','upgrade-result')});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.factor){factor=Number(b.dataset.factor);render();return}if(b.id==='collect-bank'){G.accrue(state);const amount=G.collect(state);save();render();toast(money(amount)+' abgeholt!');return}if(b.dataset.page){page=b.dataset.page;render();return}if(b.dataset.filter){filter=b.dataset.filter;render();return}if(b.id==='keep'||b.id==='close-reveal'){$('reveal').close();return}try{G.accrue(state);if(b.dataset.open!==undefined){const x=G.open(state,Number(b.dataset.open));save();render();reveal(x);return}if(b.dataset.sell){G.sell(state,b.dataset.sell);toast('Verkauft. Deine Münzen sind da.')}else if(b.dataset.deposit){G.deposit(state,b.dataset.deposit);toast('Eingelegt! Dein Fund verdient jetzt Münzen.')}else if(b.dataset.withdraw){G.withdraw(state,b.dataset.withdraw);toast('Wieder in deinem Inventar.')}else if(b.id==='buy-slot'){G.buySlot(state);toast('Ein neuer Bankplatz gehört dir.')}else if(b.id==='upgrade-button'){const result=G.upgrade(state,source,Number(target));source='';target='';save();render();if(result)reveal(result,'AUFWERTUNG GESCHAFFT!');else toast('Leider kein Treffer. Dein Einsatz ist verloren.');return}else return;save();render()}catch(err){toast(err.message)}});
document.addEventListener('change',e=>{if(e.target.id==='source'){source=e.target.value;target='';render()}if(e.target.id==='target'){target=e.target.value;render()}});document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;renderAlbum()}});

const inventoryStyle=document.createElement('link');inventoryStyle.rel='stylesheet';inventoryStyle.href='inventory.css';document.head.appendChild(inventoryStyle);
let invQuery='',invKind='',invTier='',invSort='new',invOnly='';const picked=new Set();
function inventoryList(){return state.inventory.map((x,index)=>({...x,index})).filter(x=>{const i=G.catalog[x.id];return (i.name+' '+i.kind).toLowerCase().includes(invQuery.toLowerCase())&&(!invKind||i.kind===invKind)&&(!invTier||String(i.tier)===invTier)&&(!invOnly||(invOnly==='favorite'?x.favorite:x.locked))}).sort((a,b)=>invSort==='value'?G.catalog[b.id].value-G.catalog[a.id].value:invSort==='low'?G.catalog[a.id].value-G.catalog[b.id].value:invSort==='rarity'?G.catalog[b.id].tier-G.catalog[a.id].tier:invSort==='name'?G.catalog[a.id].name.localeCompare(G.catalog[b.id].name):b.index-a.index)}
function renderInventory(el){
 el.innerHTML=heading('DEINE SCHÄTZE','Ordnung in der Sammelstube.','Markiere deine Lieblinge und schütze besondere Funde vor Verkauf und Aufwertung.')+`<div class="inventory-tools"><label>Suche<input id="inv-query" type="search" value="${esc(invQuery)}" placeholder="Name oder Gegenstandsart"></label><label>Gegenstandsart<select id="inv-kind"><option value="">Alle Arten</option>${['Waffe','Messer','Handschuhe'].map(x=>`<option ${invKind===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Seltenheit<select id="inv-tier"><option value="">Alle Seltenheiten</option>${G.tiers.map((x,i)=>`<option value="${i}" ${invTier===String(i)?'selected':''}>${x.name}</option>`).join('')}</select></label><label>Sortieren<select id="inv-sort">${[['new','Neueste zuerst'],['value','Wert: hoch → niedrig'],['low','Wert: niedrig → hoch'],['rarity','Seltenste zuerst'],['name','Name A–Z']].map(([v,t])=>`<option value="${v}" ${invSort===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Anzeigen<select id="inv-only"><option value="">Alle Funde</option><option value="favorite" ${invOnly==='favorite'?'selected':''}>Nur Favoriten</option><option value="locked" ${invOnly==='locked'?'selected':''}>Nur geschützte</option></select></label></div><div id="inventory-results"></div>`;
 renderInventoryResults();
}
function renderInventoryResults(){
 const list=inventoryList();for(const uid of picked)if(!list.some(x=>x.uid===uid))picked.delete(uid);
 const selection=state.inventory.filter(x=>picked.has(x.uid)),sum=selection.reduce((v,x)=>v+G.catalog[x.id].value,0);
 $('inventory-results').innerHTML=`<div class="section-title"><h2>Inventar <span>${list.length} / ${state.inventory.length}</span></h2><span>${money(state.inventory.reduce((v,x)=>v+G.catalog[x.id].value,0))} Gesamtwert</span></div><div class="bulk-bar"><button data-inv-action="all">Sichtbare auswählen</button><button data-inv-action="clear" ${!picked.size?'disabled':''}>Auswahl aufheben</button><strong>${picked.size} ausgewählt · ${money(sum)}</strong><button data-inv-action="sell" ${!picked.size||selection.some(x=>x.locked)?'disabled':''}>Auswahl verkaufen</button><button data-inv-action="deposit" ${!picked.size?'disabled':''}>Auswahl zur Bank</button><small>Freie Bankplätze: ${state.slots-state.bank.length} · Geschützte Funde können eingelagert, aber nicht verkauft oder aufgewertet werden.</small></div><div class="item-grid">${list.map(x=>{const i=G.catalog[x.id];return `<article class="item-card inventory-card ${picked.has(x.uid)?'picked':''}"><div class="item-controls"><label><input type="checkbox" data-pick="${x.uid}" ${picked.has(x.uid)?'checked':''} aria-label="${i.name} auswählen"> Auswahl</label><button data-flag="favorite" data-uid="${x.uid}" aria-pressed="${!!x.favorite}" aria-label="${i.name} als Favorit markieren">${x.favorite?'★':'☆'}</button><button data-flag="locked" data-uid="${x.uid}" aria-pressed="${!!x.locked}">${x.locked?'Entsperren':'Schützen'}</button></div>${art(i)}<div class="item-info"><small style="color:${G.tiers[i.tier].color}">${G.tiers[i.tier].name}${x.locked?' · GESCHÜTZT':''}</small><h3>${i.name}</h3><p>${money(i.value)}</p><div class="item-actions"><button data-sell="${x.uid}" ${x.locked?'disabled':''}>Verkaufen</button><button data-deposit="${x.uid}">Zur Bank ↗</button></div></div></article>`}).join('')}</div>${!list.length?'<div class="empty"><h2>Keine passenden Funde.</h2><p>Öffne eine Kiste oder passe deine Filter an.</p></div>':''}`;
}
document.addEventListener('input',e=>{if(e.target.id==='inv-query'){invQuery=e.target.value;renderInventoryResults()}});
document.addEventListener('change',e=>{const k=e.target.id;if(k==='inv-kind')invKind=e.target.value;else if(k==='inv-tier')invTier=e.target.value;else if(k==='inv-sort')invSort=e.target.value;else if(k==='inv-only')invOnly=e.target.value;else if(e.target.dataset.pick){e.target.checked?picked.add(e.target.dataset.pick):picked.delete(e.target.dataset.pick)}else return;renderInventoryResults()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.flag){G.flag(state,b.dataset.uid,b.dataset.flag);save();renderInventoryResults();return}const action=b.dataset.invAction;if(!action)return;try{if(action==='all')inventoryList().forEach(x=>picked.add(x.uid));else if(action==='clear')picked.clear();else{if(action==='sell'&&!confirm(`Die ${picked.size} ausgewählten Gegenstände wirklich verkaufen? Dieser Verkauf kann nicht rückgängig gemacht werden.`))return;G.accrue(state);const done=G.batch(state,[...picked],action);picked.clear();save();$('inv-count').textContent=state.inventory.length;updateLive();toast(action==='sell'?`${done.count} Funde für ${money(done.total)} verkauft.`:`${done.count} Funde in die Bank gelegt.`)}renderInventoryResults()}catch(err){toast(err.message)}});

setInterval(()=>{G.accrue(state);updateLive();save()},1000);window.addEventListener('pagehide',()=>{G.accrue(state);save()});save();render();
